import 'package:d4rt/d4rt.dart';
import 'package:flutter/material.dart';

/// Returns the BridgedClass for the Flutter Icons class with comprehensive icon support.
BridgedClass getIconsBridgingDefinition() {
  return BridgedClass(
    nativeType: Icons,
    name: 'Icons',
    staticGetters: {
      // NAVIGATION ICONS
      'add': (visitor) => Icons.add,
      'remove': (visitor) => Icons.remove,
      'close': (visitor) => Icons.close,
      'menu': (visitor) => Icons.menu,
      'home': (visitor) => Icons.home,
      'arrow_back': (visitor) => Icons.arrow_back,
      'arrow_forward': (visitor) => Icons.arrow_forward,
      'arrow_upward': (visitor) => Icons.arrow_upward,
      'arrow_downward': (visitor) => Icons.arrow_downward,
      'arrow_left': (visitor) => Icons.arrow_left,
      'arrow_right': (visitor) => Icons.arrow_right,
      'keyboard_arrow_up': (visitor) => Icons.keyboard_arrow_up,
      'keyboard_arrow_down': (visitor) => Icons.keyboard_arrow_down,
      'keyboard_arrow_left': (visitor) => Icons.keyboard_arrow_left,
      'keyboard_arrow_right': (visitor) => Icons.keyboard_arrow_right,
      'expand_less': (visitor) => Icons.expand_less,
      'expand_more': (visitor) => Icons.expand_more,
      'more_vert': (visitor) => Icons.more_vert,
      'more_horiz': (visitor) => Icons.more_horiz,
      'first_page': (visitor) => Icons.first_page,
      'last_page': (visitor) => Icons.last_page,
      'chevron_left': (visitor) => Icons.chevron_left,
      'chevron_right': (visitor) => Icons.chevron_right,
      'arrow_back_ios': (visitor) => Icons.arrow_back_ios,
      'arrow_forward_ios': (visitor) => Icons.arrow_forward_ios,
      'arrow_drop_down': (visitor) => Icons.arrow_drop_down,
      'arrow_drop_up': (visitor) => Icons.arrow_drop_up,
      'arrow_drop_down_circle': (visitor) => Icons.arrow_drop_down_circle,

      // ACTION ICONS
      'edit': (visitor) => Icons.edit,
      'delete': (visitor) => Icons.delete,
      'save': (visitor) => Icons.save,
      'search': (visitor) => Icons.search,
      'settings': (visitor) => Icons.settings,
      'favorite': (visitor) => Icons.favorite,
      'favorite_border': (visitor) => Icons.favorite_border,
      'share': (visitor) => Icons.share,
      'refresh': (visitor) => Icons.refresh,
      'check': (visitor) => Icons.check,
      'clear': (visitor) => Icons.clear,
      'done': (visitor) => Icons.done,
      'cancel': (visitor) => Icons.cancel,
      'info': (visitor) => Icons.info,
      'warning': (visitor) => Icons.warning,
      'error': (visitor) => Icons.error,
      'copy': (visitor) => Icons.copy,
      'paste': (visitor) => Icons.paste,
      'content_copy': (visitor) => Icons.content_copy,
      'undo': (visitor) => Icons.undo,
      'redo': (visitor) => Icons.redo,
      'print': (visitor) => Icons.print,
      'zoom_in': (visitor) => Icons.zoom_in,
      'zoom_out': (visitor) => Icons.zoom_out,
      'fullscreen': (visitor) => Icons.fullscreen,
      'fullscreen_exit': (visitor) => Icons.fullscreen_exit,
      'launch': (visitor) => Icons.launch,
      'open_in_new': (visitor) => Icons.open_in_new,
      'build': (visitor) => Icons.build,
      'bug_report': (visitor) => Icons.bug_report,
      'code': (visitor) => Icons.code,
      'sync': (visitor) => Icons.sync,
      'sync_alt': (visitor) => Icons.sync_alt,
      'backup': (visitor) => Icons.backup,
      'restore': (visitor) => Icons.restore,
      'update': (visitor) => Icons.update,
      'create': (visitor) => Icons.create,
      'create_new_folder': (visitor) => Icons.create_new_folder,

      // COMMUNICATION ICONS
      'email': (visitor) => Icons.email,
      'phone': (visitor) => Icons.phone,
      'chat': (visitor) => Icons.chat,
      'message': (visitor) => Icons.message,
      'send': (visitor) => Icons.send,
      'call': (visitor) => Icons.call,
      'call_end': (visitor) => Icons.call_end,
      'video_call': (visitor) => Icons.video_call,
      'forum': (visitor) => Icons.forum,
      'contact_mail': (visitor) => Icons.contact_mail,
      'contact_phone': (visitor) => Icons.contact_phone,
      'mail_outline': (visitor) => Icons.mail_outline,
      'textsms': (visitor) => Icons.textsms,
      'comment': (visitor) => Icons.comment,
      'chat_bubble': (visitor) => Icons.chat_bubble,
      'chat_bubble_outline': (visitor) => Icons.chat_bubble_outline,

      // MEDIA ICONS
      'play_arrow': (visitor) => Icons.play_arrow,
      'pause': (visitor) => Icons.pause,
      'stop': (visitor) => Icons.stop,
      'skip_next': (visitor) => Icons.skip_next,
      'skip_previous': (visitor) => Icons.skip_previous,
      'fast_forward': (visitor) => Icons.fast_forward,
      'fast_rewind': (visitor) => Icons.fast_rewind,
      'replay': (visitor) => Icons.replay,
      'shuffle': (visitor) => Icons.shuffle,
      'repeat': (visitor) => Icons.repeat,
      'repeat_one': (visitor) => Icons.repeat_one,
      'volume_up': (visitor) => Icons.volume_up,
      'volume_down': (visitor) => Icons.volume_down,
      'volume_off': (visitor) => Icons.volume_off,
      'volume_mute': (visitor) => Icons.volume_mute,
      'movie': (visitor) => Icons.movie,
      'music_note': (visitor) => Icons.music_note,
      'library_music': (visitor) => Icons.library_music,
      'playlist_play': (visitor) => Icons.playlist_play,
      'mic': (visitor) => Icons.mic,
      'mic_off': (visitor) => Icons.mic_off,
      'headset': (visitor) => Icons.headset,
      'speaker': (visitor) => Icons.speaker,
      'radio': (visitor) => Icons.radio,
      'album': (visitor) => Icons.album,
      'audiotrack': (visitor) => Icons.audiotrack,
      'equalizer': (visitor) => Icons.equalizer,

      // FILES & FOLDERS
      'folder': (visitor) => Icons.folder,
      'folder_open': (visitor) => Icons.folder_open,
      'folder_shared': (visitor) => Icons.folder_shared,
      'insert_drive_file': (visitor) => Icons.insert_drive_file,
      'attach_file': (visitor) => Icons.attach_file,
      'download': (visitor) => Icons.download,
      'upload': (visitor) => Icons.upload,
      'cloud': (visitor) => Icons.cloud,
      'cloud_download': (visitor) => Icons.cloud_download,
      'cloud_upload': (visitor) => Icons.cloud_upload,
      'cloud_done': (visitor) => Icons.cloud_done,
      'cloud_off': (visitor) => Icons.cloud_off,
      'file_copy': (visitor) => Icons.file_copy,
      'description': (visitor) => Icons.description,

      // PERSON & ACCOUNT ICONS
      'person': (visitor) => Icons.person,
      'person_add': (visitor) => Icons.person_add,
      'person_remove': (visitor) => Icons.person_remove,
      'person_outline': (visitor) => Icons.person_outline,
      'group': (visitor) => Icons.group,
      'group_add': (visitor) => Icons.group_add,
      'account_circle': (visitor) => Icons.account_circle,
      'account_box': (visitor) => Icons.account_box,
      'face': (visitor) => Icons.face,
      'supervisor_account': (visitor) => Icons.supervisor_account,
      'people': (visitor) => Icons.people,
      'people_outline': (visitor) => Icons.people_outline,
      'family_restroom': (visitor) => Icons.family_restroom,

      // TIME & DATE ICONS
      'access_time': (visitor) => Icons.access_time,
      'schedule': (visitor) => Icons.schedule,
      'today': (visitor) => Icons.today,
      'date_range': (visitor) => Icons.date_range,
      'event': (visitor) => Icons.event,
      'event_available': (visitor) => Icons.event_available,
      'event_busy': (visitor) => Icons.event_busy,
      'timer': (visitor) => Icons.timer,
      'alarm': (visitor) => Icons.alarm,
      'alarm_add': (visitor) => Icons.alarm_add,
      'alarm_off': (visitor) => Icons.alarm_off,
      'alarm_on': (visitor) => Icons.alarm_on,
      'history': (visitor) => Icons.history,
      'watch_later': (visitor) => Icons.watch_later,
      'pending': (visitor) => Icons.pending,
      'hourglass_empty': (visitor) => Icons.hourglass_empty,
      'hourglass_full': (visitor) => Icons.hourglass_full,

      // IMAGE & CAMERA ICONS
      'image': (visitor) => Icons.image,
      'photo': (visitor) => Icons.photo,
      'photo_camera': (visitor) => Icons.photo_camera,
      'camera_alt': (visitor) => Icons.camera_alt,
      'videocam': (visitor) => Icons.videocam,
      'videocam_off': (visitor) => Icons.videocam_off,
      'photo_library': (visitor) => Icons.photo_library,
      'collections': (visitor) => Icons.collections,
      'crop': (visitor) => Icons.crop,
      'crop_free': (visitor) => Icons.crop_free,
      'rotate_left': (visitor) => Icons.rotate_left,
      'rotate_right': (visitor) => Icons.rotate_right,
      'flip': (visitor) => Icons.flip,
      'filter': (visitor) => Icons.filter,
      'palette': (visitor) => Icons.palette,
      'color_lens': (visitor) => Icons.color_lens,
      'brush': (visitor) => Icons.brush,
      'flash_on': (visitor) => Icons.flash_on,
      'flash_off': (visitor) => Icons.flash_off,
      'flash_auto': (visitor) => Icons.flash_auto,

      // SHOPPING & PAYMENT ICONS
      'shopping_cart': (visitor) => Icons.shopping_cart,
      'shopping_bag': (visitor) => Icons.shopping_bag,
      'add_shopping_cart': (visitor) => Icons.add_shopping_cart,
      'remove_shopping_cart': (visitor) => Icons.remove_shopping_cart,
      'payment': (visitor) => Icons.payment,
      'credit_card': (visitor) => Icons.credit_card,
      'monetization_on': (visitor) => Icons.monetization_on,
      'attach_money': (visitor) => Icons.attach_money,
      'local_offer': (visitor) => Icons.local_offer,
      'local_atm': (visitor) => Icons.local_atm,
      'account_balance': (visitor) => Icons.account_balance,
      'account_balance_wallet': (visitor) => Icons.account_balance_wallet,
      'store': (visitor) => Icons.store,
      'storefront': (visitor) => Icons.storefront,

      // RATING & FEEDBACK ICONS
      'star': (visitor) => Icons.star,
      'star_border': (visitor) => Icons.star_border,
      'star_half': (visitor) => Icons.star_half,
      'star_outline': (visitor) => Icons.star_outline,
      'thumb_up': (visitor) => Icons.thumb_up,
      'thumb_down': (visitor) => Icons.thumb_down,
      'thumb_up_alt': (visitor) => Icons.thumb_up_alt,
      'thumb_down_alt': (visitor) => Icons.thumb_down_alt,
      'sentiment_very_satisfied': (visitor) => Icons.sentiment_very_satisfied,
      'sentiment_satisfied': (visitor) => Icons.sentiment_satisfied,
      'sentiment_neutral': (visitor) => Icons.sentiment_neutral,
      'sentiment_dissatisfied': (visitor) => Icons.sentiment_dissatisfied,
      'sentiment_very_dissatisfied': (visitor) =>
          Icons.sentiment_very_dissatisfied,

      // VISIBILITY & PRIVACY ICONS
      'visibility': (visitor) => Icons.visibility,
      'visibility_off': (visitor) => Icons.visibility_off,
      'lock': (visitor) => Icons.lock,
      'lock_open': (visitor) => Icons.lock_open,
      'lock_outline': (visitor) => Icons.lock_outline,
      'security': (visitor) => Icons.security,
      'verified': (visitor) => Icons.verified,
      'verified_user': (visitor) => Icons.verified_user,
      'vpn_key': (visitor) => Icons.vpn_key,
      'fingerprint': (visitor) => Icons.fingerprint,

      // NOTIFICATION ICONS
      'notifications': (visitor) => Icons.notifications,
      'notifications_off': (visitor) => Icons.notifications_off,
      'notifications_active': (visitor) => Icons.notifications_active,
      'notifications_none': (visitor) => Icons.notifications_none,
      'notifications_paused': (visitor) => Icons.notifications_paused,
      'notification_important': (visitor) => Icons.notification_important,

      // LISTS & ORGANIZATION
      'list': (visitor) => Icons.list,
      'list_alt': (visitor) => Icons.list_alt,
      'reorder': (visitor) => Icons.reorder,
      'sort': (visitor) => Icons.sort,
      'sort_by_alpha': (visitor) => Icons.sort_by_alpha,
      'filter_list': (visitor) => Icons.filter_list,
      'view_list': (visitor) => Icons.view_list,
      'view_module': (visitor) => Icons.view_module,
      'view_column': (visitor) => Icons.view_column,
      'view_agenda': (visitor) => Icons.view_agenda,
      'view_array': (visitor) => Icons.view_array,
      'view_carousel': (visitor) => Icons.view_carousel,
      'view_comfy': (visitor) => Icons.view_comfy,
      'view_compact': (visitor) => Icons.view_compact,
      'grid_on': (visitor) => Icons.grid_on,
      'grid_off': (visitor) => Icons.grid_off,

      // TRANSPORTATION ICONS
      'directions_car': (visitor) => Icons.directions_car,
      'directions_bus': (visitor) => Icons.directions_bus,
      'directions_bike': (visitor) => Icons.directions_bike,
      'directions_walk': (visitor) => Icons.directions_walk,
      'directions_run': (visitor) => Icons.directions_run,
      'flight': (visitor) => Icons.flight,
      'flight_takeoff': (visitor) => Icons.flight_takeoff,
      'flight_land': (visitor) => Icons.flight_land,
      'train': (visitor) => Icons.train,
      'subway': (visitor) => Icons.subway,
      'tram': (visitor) => Icons.tram,
      'local_shipping': (visitor) => Icons.local_shipping,
      'local_taxi': (visitor) => Icons.local_taxi,
      'traffic': (visitor) => Icons.traffic,
      'motorcycle': (visitor) => Icons.motorcycle,
      'electric_scooter': (visitor) => Icons.electric_scooter,

      // LOCATION & MAPS ICONS
      'location_on': (visitor) => Icons.location_on,
      'location_off': (visitor) => Icons.location_off,
      'my_location': (visitor) => Icons.my_location,
      'place': (visitor) => Icons.place,
      'map': (visitor) => Icons.map,
      'navigation': (visitor) => Icons.navigation,
      'explore': (visitor) => Icons.explore,
      'explore_off': (visitor) => Icons.explore_off,
      'gps_fixed': (visitor) => Icons.gps_fixed,
      'gps_not_fixed': (visitor) => Icons.gps_not_fixed,
      'gps_off': (visitor) => Icons.gps_off,
      'pin_drop': (visitor) => Icons.pin_drop,
      'room': (visitor) => Icons.room,
      'zoom_out_map': (visitor) => Icons.zoom_out_map,
      'zoom_in_map': (visitor) => Icons.zoom_in_map,

      // DEVICE ICONS
      'phone_android': (visitor) => Icons.phone_android,
      'phone_iphone': (visitor) => Icons.phone_iphone,
      'tablet': (visitor) => Icons.tablet,
      'tablet_android': (visitor) => Icons.tablet_android,
      'laptop': (visitor) => Icons.laptop,
      'laptop_chromebook': (visitor) => Icons.laptop_chromebook,
      'laptop_mac': (visitor) => Icons.laptop_mac,
      'laptop_windows': (visitor) => Icons.laptop_windows,
      'desktop_windows': (visitor) => Icons.desktop_windows,
      'desktop_mac': (visitor) => Icons.desktop_mac,
      'computer': (visitor) => Icons.computer,
      'tv': (visitor) => Icons.tv,
      'keyboard': (visitor) => Icons.keyboard,
      'mouse': (visitor) => Icons.mouse,
      'headphones': (visitor) => Icons.headphones,
      'watch': (visitor) => Icons.watch,
      'smartphone': (visitor) => Icons.smartphone,

      // NETWORK & CONNECTIVITY ICONS
      'wifi': (visitor) => Icons.wifi,
      'wifi_off': (visitor) => Icons.wifi_off,
      'signal_cellular_4_bar': (visitor) => Icons.signal_cellular_4_bar,
      'signal_cellular_0_bar': (visitor) => Icons.signal_cellular_0_bar,
      'signal_cellular_off': (visitor) => Icons.signal_cellular_off,
      'signal_wifi_4_bar': (visitor) => Icons.signal_wifi_4_bar,
      'signal_wifi_0_bar': (visitor) => Icons.signal_wifi_0_bar,
      'signal_wifi_off': (visitor) => Icons.signal_wifi_off,
      'bluetooth': (visitor) => Icons.bluetooth,
      'bluetooth_audio': (visitor) => Icons.bluetooth_audio,
      'bluetooth_connected': (visitor) => Icons.bluetooth_connected,
      'bluetooth_disabled': (visitor) => Icons.bluetooth_disabled,
      'bluetooth_searching': (visitor) => Icons.bluetooth_searching,
      'nfc': (visitor) => Icons.nfc,
      'usb': (visitor) => Icons.usb,

      // WEATHER ICONS
      'wb_sunny': (visitor) => Icons.wb_sunny,
      'wb_cloudy': (visitor) => Icons.wb_cloudy,
      'wb_incandescent': (visitor) => Icons.wb_incandescent,
      'ac_unit': (visitor) => Icons.ac_unit,
      'beach_access': (visitor) => Icons.beach_access,
      'opacity': (visitor) => Icons.opacity,
      'thermostat': (visitor) => Icons.thermostat,

      // BUSINESS & WORK ICONS
      'business': (visitor) => Icons.business,
      'work': (visitor) => Icons.work,
      'work_outline': (visitor) => Icons.work_outline,
      'business_center': (visitor) => Icons.business_center,
      'domain': (visitor) => Icons.domain,
      'apartment': (visitor) => Icons.apartment,
      'corporate_fare': (visitor) => Icons.corporate_fare,
      'meeting_room': (visitor) => Icons.meeting_room,
      'assignment': (visitor) => Icons.assignment,
      'assignment_turned_in': (visitor) => Icons.assignment_turned_in,
      'assessment': (visitor) => Icons.assessment,
      'analytics': (visitor) => Icons.analytics,

      // TOOLS & UTILITIES
      'construction': (visitor) => Icons.construction,
      'handyman': (visitor) => Icons.handyman,
      'engineering': (visitor) => Icons.engineering,
      'calculate': (visitor) => Icons.calculate,
      'rule': (visitor) => Icons.rule,

      // HEALTH & MEDICAL ICONS
      'local_hospital': (visitor) => Icons.local_hospital,
      'medical_services': (visitor) => Icons.medical_services,
      'health_and_safety': (visitor) => Icons.health_and_safety,
      'healing': (visitor) => Icons.healing,
      'fitness_center': (visitor) => Icons.fitness_center,
      'spa': (visitor) => Icons.spa,

      // EDUCATION ICONS
      'school': (visitor) => Icons.school,
      'class_': (visitor) => Icons.class_,
      'auto_stories': (visitor) => Icons.auto_stories,
      'menu_book': (visitor) => Icons.menu_book,
      'library_books': (visitor) => Icons.library_books,
      'book': (visitor) => Icons.book,
      'bookmark': (visitor) => Icons.bookmark,
      'bookmark_border': (visitor) => Icons.bookmark_border,

      // SPORTS & ENTERTAINMENT
      'sports': (visitor) => Icons.sports,
      'sports_soccer': (visitor) => Icons.sports_soccer,
      'sports_basketball': (visitor) => Icons.sports_basketball,
      'sports_football': (visitor) => Icons.sports_football,
      'sports_tennis': (visitor) => Icons.sports_tennis,
      'sports_golf': (visitor) => Icons.sports_golf,
      'sports_baseball': (visitor) => Icons.sports_baseball,
      'sports_volleyball': (visitor) => Icons.sports_volleyball,
      'casino': (visitor) => Icons.casino,
      'games': (visitor) => Icons.games,

      // FOOD & DINING
      'restaurant': (visitor) => Icons.restaurant,
      'restaurant_menu': (visitor) => Icons.restaurant_menu,
      'local_dining': (visitor) => Icons.local_dining,
      'local_pizza': (visitor) => Icons.local_pizza,
      'local_cafe': (visitor) => Icons.local_cafe,
      'local_bar': (visitor) => Icons.local_bar,
      'cake': (visitor) => Icons.cake,
      'kitchen': (visitor) => Icons.kitchen,

      // INTERFACE & SYSTEM ICONS
      'brightness_1': (visitor) => Icons.brightness_1,
      'brightness_2': (visitor) => Icons.brightness_2,
      'brightness_3': (visitor) => Icons.brightness_3,
      'brightness_4': (visitor) => Icons.brightness_4,
      'brightness_5': (visitor) => Icons.brightness_5,
      'brightness_6': (visitor) => Icons.brightness_6,
      'brightness_7': (visitor) => Icons.brightness_7,
      'brightness_auto': (visitor) => Icons.brightness_auto,
      'brightness_high': (visitor) => Icons.brightness_high,
      'brightness_low': (visitor) => Icons.brightness_low,
      'brightness_medium': (visitor) => Icons.brightness_medium,
      'dark_mode': (visitor) => Icons.dark_mode,
      'light_mode': (visitor) => Icons.light_mode,
      'auto_mode': (visitor) => Icons.auto_mode,
      'invert_colors': (visitor) => Icons.invert_colors,
      'invert_colors_off': (visitor) => Icons.invert_colors_off,

      // HELP & SUPPORT
      'help': (visitor) => Icons.help,
      'help_outline': (visitor) => Icons.help_outline,
      'contact_support': (visitor) => Icons.contact_support,
      'live_help': (visitor) => Icons.live_help,
      'report': (visitor) => Icons.report,
      'report_problem': (visitor) => Icons.report_problem,
      'feedback': (visitor) => Icons.feedback,

      // SETTINGS & CONFIGURATION
      'tune': (visitor) => Icons.tune,
      'admin_panel_settings': (visitor) => Icons.admin_panel_settings,
      'manage_accounts': (visitor) => Icons.manage_accounts,
      'logout': (visitor) => Icons.logout,
      'login': (visitor) => Icons.login,
      'power_settings_new': (visitor) => Icons.power_settings_new,

      // MISCELLANEOUS COMMON ICONS
      'grade': (visitor) => Icons.grade,
      'trending_up': (visitor) => Icons.trending_up,
      'trending_down': (visitor) => Icons.trending_down,
      'trending_flat': (visitor) => Icons.trending_flat,
      'label': (visitor) => Icons.label,
      'label_outline': (visitor) => Icons.label_outline,
      'new_releases': (visitor) => Icons.new_releases,
      'fiber_new': (visitor) => Icons.fiber_new,
      'tips_and_updates': (visitor) => Icons.tips_and_updates,
      'lightbulb': (visitor) => Icons.lightbulb,
      'lightbulb_outline': (visitor) => Icons.lightbulb_outline,
      'extension': (visitor) => Icons.extension,
      'widgets': (visitor) => Icons.widgets,
      'dashboard': (visitor) => Icons.dashboard,
      'apps': (visitor) => Icons.apps,
      'api': (visitor) => Icons.api,
      'webhook': (visitor) => Icons.webhook,
      'integration_instructions': (visitor) => Icons.integration_instructions,
      'task_alt': (visitor) => Icons.task_alt,
      'check_circle': (visitor) => Icons.check_circle,
      'check_circle_outline': (visitor) => Icons.check_circle_outline,
      'radio_button_checked': (visitor) => Icons.radio_button_checked,
      'radio_button_unchecked': (visitor) => Icons.radio_button_unchecked,
      'square': (visitor) => Icons.square,
      'circle': (visitor) => Icons.circle,
    },
  );
}
